spring.application.name=skypro-Demo-DataBase-Of-Hogwarts-2
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql
spring.jpa.hibernate.ddl-auto=update